<?php

declare(strict_types=1);

namespace Kylesean\Jwt\Tests;

use DateTimeImmutable;
use Kylesean\Jwt\Token as OurToken; // Token class to test
use Lcobucci\JWT\Configuration;
use Lcobucci\JWT\Signer\Hmac\Sha256;
use Lcobucci\JWT\Signer\Key\InMemory;
use Lcobucci\JWT\Token\DataSet; // Used to create lcobucci Token claims
use Lcobucci\JWT\Token\Plain; // lcobucci Plain Token (a type of UnencryptedToken)
use Lcobucci\JWT\Token\Signature;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;

#[CoversClass(OurToken::class)]
class TokenTest extends TestCase
{
    protected Configuration $lcobucciConfig;
    protected Plain $lcobucciPlainToken; // Underlying lcobucci Token instance
    protected OurToken $token; // Our wrapped Token instance

    protected function setUp(): void
    {
        parent::setUp();

        // Prepare a lcobucci/jwt Plain Token instance for testing
        // We can manually build it, or use Configuration and Builder
        // For simplicity here, we directly instantiate DataSet and Signature needed by Plain Token
        // In real applications, this Plain Token is generated by lcobucci Parser or Builder

        $this->lcobucciConfig = Configuration::forSymmetricSigner(
            new Sha256(),
            InMemory::plainText(bin2hex(random_bytes(32))) // Random secret key, content doesn't matter since we don't test signature validation
        );

        $originalClaims = [
            'jti' => 'test_jti_123',
            'iss' => 'http://example.com',
            'aud' => ['http://example.org', 'http://otherexample.org'],
            'sub' => 'test_subject_456',
            'iat' => new DateTimeImmutable('@' . (time() - 3600)), // 1 hour ago
            'nbf' => new DateTimeImmutable('@' . (time() - 3000)), // 50 minutes ago
            'exp' => new DateTimeImmutable('@' . (time() + 3600)), // 1 hour later
            'custom_claim' => 'custom_value',
            'another_claim' => 12345,
        ];

        // DataSet constructor expects string keys and mixed values.
        // For standard time claims, lcobucci/jwt v5 expects them to be DateTimeImmutable objects.
        $claimsForLcobucciDataSet = $originalClaims; // Directly use original claims


        $dataSet = new DataSet($claimsForLcobucciDataSet, 'encoded_header.encoded_claims');
        $headersSet = new DataSet(['typ' => 'JWT', 'alg' => 'HS256'], 'encoded_header');
        $signature = new Signature('dummy_signature_hash', 'encoded_signature');

        $this->lcobucciPlainToken = new Plain($headersSet, $dataSet, $signature);
        $this->token = new OurToken($this->lcobucciPlainToken);
    }

    public function testGetLcobucciToken(): void
    {
        $this->assertSame($this->lcobucciPlainToken, $this->token->getLcobucciToken());
    }

    public function testToStringMethod(): void
    {
        // Plain token toString() method returns "header.claims.signature"
        // Since we manually constructed it, ensure our PlainToken can correctly toString()
        // Or we can mock LcobucciPlainToken::toString() behavior
        // For realistic testing, we rely on LcobucciPlainToken actual behavior
        $this->assertEquals($this->lcobucciPlainToken->toString(), $this->token->toString());
        $this->assertEquals($this->lcobucciPlainToken->toString(), (string) $this->token); // Test __toString
    }

    public function testGetId(): void
    {
        $this->assertEquals('test_jti_123', $this->token->getId());
    }

    public function testGetIssuer(): void
    {
        $this->assertEquals('http://example.com', $this->token->getIssuer());
    }

    public function testGetAudience(): void
    {
        $this->assertEquals(['http://example.org', 'http://otherexample.org'], $this->token->getAudience());
    }

    public function testGetSubject(): void
    {
        $this->assertEquals('test_subject_456', $this->token->getSubject());
    }

    public function testGetIssuedAt(): void
    {
        $this->assertInstanceOf(DateTimeImmutable::class, $this->token->getIssuedAt());
        // Lcobucci v5 parses timestamp claims directly as DateTimeImmutable
        // Check: Lcobucci\JWT\Token\Plain->claims()->get() for standard time claims returns DateTimeImmutable
        // According to lcobucci/jwt v4 & v5, $token->claims()->get('iat') returns DateTimeImmutable object.
        $this->assertEqualsWithDelta(time() - 3600, $this->token->getIssuedAt()->getTimestamp(), 1.0);
    }

    public function testGetNotBefore(): void
    {
        $this->assertInstanceOf(DateTimeImmutable::class, $this->token->getNotBefore());
        $this->assertEqualsWithDelta(time() - 3000, $this->token->getNotBefore()->getTimestamp(), 1.0);
    }

    public function testGetExpirationTime(): void
    {
        $this->assertInstanceOf(DateTimeImmutable::class, $this->token->getExpirationTime());
        $this->assertEqualsWithDelta(time() + 3600, $this->token->getExpirationTime()->getTimestamp(), 1.0);
    }

    public function testGetClaim(): void
    {
        $this->assertEquals('custom_value', $this->token->getClaim('custom_claim'));
        $this->assertEquals(12345, $this->token->getClaim('another_claim'));
        $this->assertNull($this->token->getClaim('non_existent_claim'));
    }

    public function testHasClaim(): void
    {
        $this->assertTrue($this->token->hasClaim('custom_claim'));
        $this->assertTrue($this->token->hasClaim('jti'));
        $this->assertFalse($this->token->hasClaim('non_existent_claim'));
    }

    public function testGetAllClaims(): void
    {
        $allClaims = $this->token->getAllClaims();
        $this->assertArrayHasKey('jti', $allClaims);
        $this->assertArrayHasKey('iss', $allClaims);
        $this->assertArrayHasKey('aud', $allClaims);
        $this->assertArrayHasKey('sub', $allClaims);
        $this->assertArrayHasKey('iat', $allClaims);
        $this->assertArrayHasKey('nbf', $allClaims);
        $this->assertArrayHasKey('exp', $allClaims);
        $this->assertArrayHasKey('custom_claim', $allClaims);
        $this->assertEquals('custom_value', $allClaims['custom_claim']);

        // Verify whether getAllClaims returns raw values or DateTimeImmutable objects
        // Our Token::getAllClaims() implementation directly returns lcobucciToken->claims()->all() iteration
        // lcobucci/jwt v5 claims()->all() returns ['claimName' => mixedValue]
        // For time claims, it returns DateTimeImmutable object.
        $this->assertInstanceOf(DateTimeImmutable::class, $allClaims['iat']);
    }

    public function testGetAudienceWhenItIsSingleStringInLcobucciToken(): void
    {
        // Test compatibility when underlying aud is a single string
        $claims = ['aud' => 'http://singleaudience.org'];
        $dataSet = new DataSet($claims, 'h.c');
        $headersSet = new DataSet([], 'h');
        $signature = new Signature('hash', 'sig');
        $lcobucciTokenWithSingleAud = new Plain($headersSet, $dataSet, $signature);
        $ourToken = new OurToken($lcobucciTokenWithSingleAud);

        $this->assertEquals(['http://singleaudience.org'], $ourToken->getAudience());
    }

    public function testGettersForMissingStandardClaims(): void
    {
        // Test getter methods returning null when standard claims are missing
        $emptyDataSet = new DataSet([], 'h.c');
        $headersSet = new DataSet([], 'h');
        $signature = new Signature('hash', 'sig');
        $lcobucciTokenWithoutClaims = new Plain($headersSet, $emptyDataSet, $signature);
        $ourToken = new OurToken($lcobucciTokenWithoutClaims);

        $this->assertNull($ourToken->getId());
        $this->assertNull($ourToken->getIssuer());
        $this->assertEquals([], $ourToken->getAudience()); // Should return empty array when aud is missing
        $this->assertNull($ourToken->getSubject());
        $this->assertNull($ourToken->getIssuedAt());
        $this->assertNull($ourToken->getNotBefore());
        $this->assertNull($ourToken->getExpirationTime());
    }
}
